  on:
    push:
      tags:
        - v0.*
        - v1.*

  jobs:
    release:
      name: Build and Release
      runs-on: ubuntu-latest
      permissions:
        id-token: write
        contents: write
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        - name: Configure Java
          uses: actions/setup-java@v3
          with:
            distribution: 'zulu'
            java-version: 8
            cache: gradle
        - name: Build
          run: make
